### ISSUE TITLE
Support mouse scroll

### ISSUE THREAD

**Issue by Nashenas88** [dandavison/delta#58] opened 2019-11-20 16:52 UTC
In the default git pager (`less` on my system) I can use the mouse scroll wheel to scroll through the pager output. When `delta` is used, the mouse scroll does not work, and I'm forced to use the navigation shortcuts. It would be really nice to be able to scroll with the mouse wheel.

System: `Linux pop-os 5.3.0-22-generic #24+system76~1573659475~19.10~26b2022-Ubuntu SMP Wed Nov 13 20:0 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ronjouch** [comment] 2019-11-22 21:02
For me, using the mouse wheel, scrolling *UP* works, but *DOWN* doesn't.

Strangely, it scrolling down *does* work in a simple `less /var/log/syslog`. Something in the way `delta` invokes `less` must cause it to fail?

Using Ubuntu Linux 19.10 with less 487 and delta 0.0.14

**Comment by Darkhogg** [comment] 2019-12-03 07:42
Please. This is the one thing preventing me from using delta.

**Comment by dandavison** [comment] 2019-12-03 15:51
Hi, thanks for the report, let's get to the bottom of this. You might have to help me out a bit as I don't usually use a mouse. Are you familiar with [bat](https://github.com/sharkdp/bat)? The code in delta relating to paging is literally copied from bat, and my intention in doing that was that the two projects would behave the same in these respects. So, there are [many](https://github.com/sharkdp/bat/issues?utf8=%E2%9C%93&q=is%3Aissue+scrolling) issues in the bat github repo concerning scrolling. Ultimately, the solution the bat author recommends is described here: https://github.com/sharkdp/bat#using-a-different-pager.

Would you be able to do the following?

1. Try out bat and see if you find the same problems with scrolling there as with delta.
2. Tell me if the solution recommended by bat works for you in delta.

Maybe you could help me understand something: I've read the various bat issues but I don't think I understand what people mean when they talk about "scrolling in less". I have just located a mouse and I find (in MacOS iTerm2 and Terminal.app) that the scroll wheel scrolls the terminal application's main scroll bar, and so "scrolling works" in a sense for delta, less and bat.

**Comment by Darkhogg** [comment] 2019-12-03 23:54
Tried to use bat, same problem as with delta.
Tried to set `export BAT_PAGER="less -irRSx4"`, where the less options were copied from my `$LESS` env var, worked like a charm.

Try to run `less -irRSx4` with a big file to see what we mean by scrolling, BTW.

**Comment by dandavison** [comment] 2019-12-04 00:33
> worked like a charm.

OK, just to be clear, did it work like a charm in both delta and bat? (It should.) So maybe we can close this issue by updating the README to explain that the solution is the same as bat?

**Comment by ronjouch** [comment] 2019-12-04 15:09
> Did `export BAT_PAGER="less -irRSx4"` work like a charm in both delta and bat? (It should.) So maybe we can close this issue by updating the README to explain that the solution is the same as bat?

@dandavison @Darkhogg thanks! I confirm that `export BAT_PAGER="less -rR"` fixes mouse wheel scrolling in both `delta` (e.g. showing a big diff) and raw `bat` (e.g. `ls /usr/bin | bat`). Notes:

- Options `i`, `S` and `x4` mentioned by @Darkhogg are unrelated.
- `less`' manpage suggests there is a nuance between `r` and `R`, but I couldn't be bothered to understand it. Both work fix mouse wheel scrolling, and [bat's README suggests to use -R](https://github.com/sharkdp/bat#using-a-different-pager)
- Actually, [bat's README suggests to use -RFX and maybe -S](https://github.com/sharkdp/bat#using-a-different-pager) but, for me (Ubuntu 19.10), F causes null output, X breaks mouse scroll, and S doesn't fix it (😄). So for me `export BAT_PAGER="less -iRx4"` it is.

@dandavison a mention in the README seems appropriate to me too. Thanks for delta!!!

**Comment by Darkhogg** [comment] 2019-12-04 16:41
Oh, nice, I didn't realize that was supposed to make delta work, I just tried bat.
To confirm: It works in delta too, just checked.
The fact that I have to use a bat env var for this is a bit confusing but I'll take it.

**Comment by dandavison** [comment] 2019-12-04 18:06
@Darkhogg @ronjouch awesome, I'll add the explanation to the README.

@Darkhogg You actually don't have to use a bat env var; delta  also honors the standard Unix `PAGER` env var (giving precedence to `BAT_PAGER`). And bat also honors both of them with the same precedence rule. My thinking was that adding a `DELTA_PAGER` to this would have been unnecessarily confusing :)

In general, my intention is for delta in some ways to be a companion tool to bat. bat does not implement language-specific syntax highlighting for diff output, or for the multi-language diff output produced by `git diff` (see https://github.com/sharkdp/bat/issues/23), since it's a different problem from the syntax-highlighting-a-single-language-file problem that bat solves. But both bat and delta are written in Rust and, since they both use [syntect](https://github.com/trishume/syntect), they use the same format for color themes and language syntax descriptions. So, my intention is basically that a bat user's bat configuration will, where appropriate, be honored automatically by delta. So far, that is true for `BAT_PAGER`, and I plan to make delta read custom themes and syntax definitions from the same location as bat (`~/.cache/bat`), so that the same process can be used for adding new themes/languages: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions. I'd be happy to hear any thoughts on whether this makes sense.

**Comment by ronjouch** [comment] 2019-12-04 18:25
> @Darkhogg You actually don't have to use a bat env var; delta also honors the standard Unix `PAGER` env var (giving precedence to `BAT_PAGER`). And bat also honors both of them with the same precedence rule.

Hmmm yes, and bat is supposed to user `PAGER` too, see [bat's README / Using a different pager](https://github.com/sharkdp/bat#using-a-different-pager)). However, setting `PAGER` to `less -iRx4` didn't fix scrolling in bat, I did have to set `BAT_PAGER` to fix it. Not sure what's going on, maybe bat's handling of `PAGER` is confused by arguments?

**Comment by dandavison** [comment] 2019-12-04 18:45
@ronjouch is that the effect of the precedence rule? Is `PAGER` honored if you do `unset BAT_PAGER` first (assuming you're using bash).

As an extra level of complexity, I believe that for `bat`, setting the env vars to empty string (e.g. `export BAT_PAGER=`) will not cause them to be ignored: they have to be literally not set / unset. But for delta, I have made delta ignore the env vars if they are empty. I hadn't thought it through sufficiently to decide whether I should open an issue against bat or not.

**Comment by ronjouch** [comment] 2019-12-04 18:53
@dandavison I'm using the fish shell, and I tested my change in a fresh session after editing my config.fish :

- With `BAT_PAGER` set to `less -iRx4` (and `PAGER` unset), mouse scrolling works in `ls -la /usr/bin`
- With `PAGER` set to `less -iRx4` (and `BAT_PAGER` unset), mouse scrolling doesn't work in `ls -la /usr/bin`

**Comment by Nashenas88** [comment] 2019-12-04 19:05
For me, setting `BAT_PAGER='less -R'` works. `PAGER` isn't respected for me.

**Comment by dandavison** [comment] 2019-12-04 19:22
Ah sorry, that's right, bat (and therefore delta, which uses a bat's code here) [replaces the arguments to less](https://github.com/sharkdp/bat/blob/master/src/output.rs#L32-L45) when `PAGER` is the only env var set. OK, it's all a bit confusing, and there's the `--pager` argument which bat has and delta does not currently. So plenty of degrees of freedom...

I'm glad we have a solution here and I'll ping this ticket again when I add an explanation to the README. (Unless someone else wants to which would also be great).

**Closed** 2019-12-04 19:44 UTC

**Comment by dandavison** [comment] 2019-12-04 19:46
I think this issue can stay closed now. Thanks all and thanks @ronjouch who added a section on mouse scrolling to the README.

**Comment by danielsanfr** [comment] 2020-06-04 02:02
Hello people. First, what an incredible tool this is!

I know this is probably not a problem in delta, but if anyone can help me, I will be very grateful.

**I'm using fish as my main shell,** and my problem follows below:

If I set the EV using `set -Ux BAT_PAGER "less -RF"`, then call zsh, the diff will be the way I want it.
So if inside the zsh I call the fish, the diff is also the way I want it.
However if I call the exit from fish to zsh and call the exit again to go back to the initial (or main) fish, the diff does not work the way I want.

I tried to set the environment variable through the `~/.config/fish/config.fish` file but I also got the same behavior reported above.

I decided to ask here, because maybe if I had the `--pager` option, I could solve this problem as `delta --pager="less -RF"`.

**Comment by brkn** [comment] 2020-08-26 18:57
My less version was `less 487` on MacOS.
```
less --version
less 487 (POSIX regular expressions)
```

I just installed `less` from brew and linked it. Now scrolling just works. 

```sh
brew install less
brew link less
```

```sh
less --version
less 551 (PCRE regular expressions)
Copyright (C) 1984-2019  Mark Nudelman
```

**Comment by freak4pc** [comment] 2020-10-05 16:16
Wonderful wonderful tool. I can't get scrolling to work on `zsh`. Tried `less -iRx4` and `less -R` for `BAT_PAGER`. Happy to try anything else if you have thought :) Thanks all.

**Comment by Kr1ss-XD** [comment] 2020-10-05 17:18
@freak4pc You could try to append `'--mouse'` or `'--MOUSE'` to the `LESS` environment variable, depending on the direction you to use your mouse wheel in. :wink:

Your terminal emulator needs to support mouse events for this to work, of course.

The number of lines to scroll with the wheel can be adjusted with `--wheel-lines=<n>`.

**Comment by OliverJAsh** [comment] 2021-07-27 12:15
Mac user here. I tried the steps outlined in the docs (install latest `less` and/or `BAT_PAGER='less -R'`) to no avail.

However, I did manage to get it working with `BAT_PAGER='less -+X'`.

This is the same fix as suggested in this issue for `diff-so-fancy`: https://github.com/so-fancy/diff-so-fancy/issues/246.

**Comment by gabriel-del** [comment] 2023-07-09 16:41
It worked to me with:

**Comment by gabriel-del** [comment] 2023-07-09 16:41
a

**Comment by gabriel-del** [comment] 2023-07-09 16:44
It worked to me with:

```
export DELTA_PAGER="less --mouse"
```

On **~/.bashrc**

**Comment by calestyo** [comment] 2023-10-10 14:51
Hey there.

When I use e.g.  `DELTA_PAGER='less --mouse'`, then scrolling in `delta` works for me, however it doesn't without, which is strange, as both my `bat` and `less` do support mouse scrolling out of the box.

```
188565 pts/8    S+     0:00 git diff HEAD~10
 188566 pts/8    Sl+    0:00 /usr/bin/delta
 188570 pts/8    S+     0:00 less --RAW-CONTROL-CHARS --quit-if-one-screen
```
Apparently my delta uses `less` per default and adds ` --RAW-CONTROL-CHARS --quit-if-one-screen`, but even with these options a standalone `less` on some file has working mouse scrolling support.

There are no aliases or so, that would cause that.

Cheers,
Chris.

**Comment by dandavison** [comment] 2023-10-10 21:42
Hi @calestyo, hm, definitely the same version of `less` being used? Have you checked what `ps` says for the other scenarios? Is it possible you have something in `LESS`? There's some good discussion in this thread: https://github.com/dandavison/delta/issues/630?

**Comment by calestyo** [comment] 2023-10-11 00:51
Hey @dandavison 

With my standalone `less` and aliases cleared I got:
```
 223440 pts/10   S+     0:00 less
```
so no parameters, and:
```
$ cat /proc/223440/environ  | tr '\0' '\n' | grep -Ei 'pager|less|delta'
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/less
```
But these shouldn't affect scrolling (which works).


At the same time for `delta` via `git`:
```
 225803 pts/13   S+     0:00 git diff HEAD~10
 225804 pts/13   Sl+    0:00 /usr/bin/delta
 225808 pts/13   S+     0:00 less --RAW-CONTROL-CHARS --quit-if-one-screen
 ```
with:
```
$ cat /proc/225808/environ  | tr '\0' '\n' | grep -Ei 'pager|less|delta'
LESS=FRX
LESSANSIENDCHARS=mK
LESSCHARSET=UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSHISTFILE=/home/calestyo/.local/share/delta/lesshst
LESSOPEN=| /usr/bin/lesspipe %s
```
(with scrolling **not** working)

Now `delta` alone:
```
$ git format-patch HEAD~10 --stdout > foo.patch
$ cat foo.patch | delta 
```
gives:
```
 228058 pts/7    Sl+    0:00 delta
 228062 pts/7    S+     0:00 less --RAW-CONTROL-CHARS --quit-if-one-screen
```
with:
```
$ cat /proc/228062/environ  | tr '\0' '\n' | grep -Ei 'pager|less|delta'
LESSANSIENDCHARS=mK
LESSCHARSET=UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSHISTFILE=/home/calestyo/.local/share/delta/lesshst
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/delta
```
(with scrolling working).


Now I played around and set `LESS` manually to combinations of `FRX` and ran `cat foo.patch | delta`.

It's the `X` in `LESS` that breaks scrolling.


Next I wanted to see whether `git` is the "offender" ;-) who sets the `X`, and from my `git_config` where I have these with respect to `delta`:
```
[core]
        pager = delta
…
[interactive]
       diffFilter = delta --color-only
…
[delta]
        navigate = true
```
I accidentally commented only:
```
[interactive]
       diffFilter = delta --color-only
```
(which I merely have because of `delta`’s `README.md`)

But that's already it, with that, I get:
```
 231643 pts/7    S+     0:00 git diff HEAD~10
 231644 pts/7    Sl+    0:00 /usr/bin/delta
 231648 pts/7    S+     0:00 less --RAW-CONTROL-CHARS --quit-if-one-screen
```
and:
```
$ cat /proc/231648/environ  | tr '\0' '\n' | grep -Ei 'pager|less|delta'
LESS=FR
LESSANSIENDCHARS=mK
LESSCHARSET=UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSHISTFILE=/home/calestyo/.local/share/delta/lesshst
LESSOPEN=| /usr/bin/lesspipe %s
```

So I'd guess it's in fact `delta`, which adds the `X` when `--color-only` is used?!

Is it really needed (I guess so)?

And if, couldn’t you just also add `--mouse`?<br>
That would make behave more like people expect from `less`.

At least my `less` scrolls per default, even without `--mouse`). I looked into that, and it seems to be a VTE speciality (presumably it sends UP and DOWN?).<br>
Trying it in `xterm` and my `less` no longer scrolls per default (unless `--mouse` is given).

So probably, you should actually **not** not add `--mouse`, unless perhaps you detected that VTE is used (e.g. via the `VTE_VERSION` env var).<br>
But problem with that would still be, that there'd be no longer a direct way for people do specifically disable mouse scrolling (there is no `--no-mouse` option, so you'd need to add some option to `delta` to disable that quirk).

Yeah not really sure what would be the best way to go.

Cheers,
Chris.

**Comment by dandavison** [comment] 2023-10-11 06:22
Hm, neither delta nor bat alter the `LESS` env var.

Also my understanding is that the `[interactive]` stanza in gitconfig is only in effect during operations such as `git add -p` or `--interactive`.

Could you double check the part of your experiment where you found that

```gitconfig
[interactive]
       diffFilter = delta --color-only
```

adds `X` to the `LESS` env var under a `git diff` invocation? I don't think that should be the case.

**Comment by calestyo** [comment] 2023-10-11 22:21
Uhm... I have no idea how I've managed to mess that up ^^ (=sorry)<br>
Trying it again, I couldn't reproduce it.

So dug further and found:
https://github.com/git/git/blob/aab89be2eb6ca51eefeb8c8066f673f447058856/Documentation/config/core.txt#L550-L562

So git is the "offender" ;-) ... an in fact, even the `delta` process has the env var already set to `FRX`.

I've [asked](https://lore.kernel.org/git/3a2c362c019338ca7408b7a3bc5715b535d15b8a.camel@scientia.org/T/#u) at the git mailing list, why they even add `X`, presumably to avoid clearing the screen after exiting.

Next I'd ask less upstream, why `X` causes VTE’s scrolling to break, and whether there's some out-of-the-box solution.

**Comment by dandavison** [comment] 2023-10-12 08:15
Ok great, that's progress!

**Comment by RReverser** [comment] 2023-10-22 12:10
Hm is there any cross-platform solution that would work on Windows? (like native Rust tools do) `less` is not really an option here unless I install from GNU utils or something.

**Comment by injust** [comment] 2024-07-01 15:40
After reading a lot of threads, passing `--redraw-on-quit` to `less` instead of `-X` was the minimal and best solution I found. You can do this by changing `core.pager` from `delta` to `LESS='FR --redraw-on-quit' delta`.

git sets `LESS=FRX` by default. One workaround is to add `--mouse`, but this results in unnatural scrolling (explanation in https://github.com/gwsw/less/issues/445#issuecomment-1758887183). You can "fix" it with `--wheel-lines=N`, but because `--mouse` scrolling is handled by `less`, you lose native scrolling features like inertia (very noticeable on a touchpad).

The better solution is to replace `-X` with `--redraw-on-quit`. This maintains native scrolling. You do need a new-enough version of `less` that has this option, though.

---

Sorry for necroing, but I figured this was useful information to have here (especially as https://dandavison.github.io/delta/tips-and-tricks/mouse-scrolling.html points to this issue).
