### ISSUE TITLE
🚀 Windows: Delta default settings hard to read

### ISSUE THREAD

**Issue by lesleyrs** [dandavison/delta#1488] opened 2023-07-24 20:16 UTC
git diff (delta)
![image](https://github.com/dandavison/delta/assets/19632758/f377287a-78ba-41b9-b4c8-afd36fa1eb88)
git diff | delta --side-by-side --diff-highlight
![image](https://github.com/dandavison/delta/assets/19632758/87ae4612-c869-46dc-90a0-e2b91c699b8a)
git diff | delta --side-by-side --diff-so-fancy
![image](https://github.com/dandavison/delta/assets/19632758/f8606b25-895a-4f31-b097-d8f3b88d0873)

The above are much harder to read than without delta, although there's no side-by-side feature:
![image](https://github.com/dandavison/delta/assets/19632758/4c01c49c-adcd-47f6-aca9-6ba36327fecf)

With default settings I mean this: https://github.com/dandavison/delta#get-started

**Comment by dandavison** [comment] 2023-08-01 12:09
Hi @lesleyrs, if I understand correctly I think you're highlighting two issues here:

1. When using a dark terminal background with default delta theme, the contrast between background colors and highlighted background sections, and foreground text in delta can be a bit poor. I agree; please have a look at the custom themes that users have created:  https://dandavison.github.io/delta/custom-themes.html and also see https://github.com/dandavison/delta/issues/481

2. When you use `--side-by-side --diff-highlight` something is wrong with your color output. This is not a bug in delta; I think your terminal emulator is failing to display something correctly; perhaps it doesn't support 24-bit color ("truecolor"). See https://dandavison.github.io/delta/tips-and-tricks/24-bit-color-truecolor.html


I would love help with finding better dark-background defaults. Honestly that might be one of the biggest improvements to delta that could be made since most people use dark terminal backgrounds (for whateven reason I use light backgrounds and delta is very readable with the default light theme; do try that if you are not opposed to light backgrounds).

I'll close this since the subject is addressed in the links above, and I believe that the display bug you're seeing is not a delta bug. But I'm always happy to continue discussing in closed tickets.

**Closed by dandavison** 2023-08-01 12:09 UTC
