### ISSUE TITLE
🐛 Line numbers incorrect/relative - Windows/Delta 0.4.1

### ISSUE THREAD

**Issue by iyerusad** [dandavison/delta#293] opened 2020-08-14 23:41 UTC
Line numbers seem to be incorrect/relative in delta output. I believe this a bug, but apologies if just expected behavior.

Examples:
---
**git diff** (line numbers should be like 500 or so)
![image](https://user-images.githubusercontent.com/25647368/90299339-f2c67b80-de52-11ea-97e7-55359d441cf8.png)

**git show** (line numbers should be like at like 330 or so)
![image](https://user-images.githubusercontent.com/25647368/90299405-315c3600-de53-11ea-9de1-df95e1879cf0.png)

**git show --no-pager**
![image](https://user-images.githubusercontent.com/25647368/90299678-3a99d280-de54-11ea-8e7f-f43a369ac9c2.png)

Configs:
--
Delta 0.4.1 - Windows, executable from github release added to PATH.

**delta --show-config:**
![image](https://user-images.githubusercontent.com/25647368/90299485-7c764900-de53-11ea-9226-0aabaddbd517.png)

**git config --list**
```
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.autocrlf=input
core.fscache=true
core.symlinks=false
pull.rebase=false
core.editor="C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
core.autocrlf=false
core.eol=lf
winupdater.recentlyseenversion=2.25.0.windows.1

include.path=~/.dotfiles/git/git_tweaks
diff.mnemonicprefix=true
diff.algorithm=patience
push.default=simple
log.date=auto:format:%a %Y-%h-%d %I:%M %p %z %Z

include.path=~/.dotfiles/git/git_deltadiff
interactive.difffilter=delta --color-only
delta.features=side-by-side line-numbers decorations
delta.syntax-theme=Dracula
delta.plus-style=syntax #003800
delta.minus-style=syntax #3f0001
delta.hunk-header-style=omit
delta.decorations.commit-decoration-style=bold yellow box ul
delta.decorations.file-style=bold yellow ul
delta.decorations.file-decoration-style=none
delta.decorations.hunk-header-decoration-style=cyan box ul
delta.line-numbers.line-numbers-left-style=cyan
delta.line-numbers.line-numbers-right-style=cyan
delta.line-numbers.line-numbers-minus-style=124
delta.line-numbers.line-numbers-plus-style=28

core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=<snipped>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
user.name=<snipped>
user.email=<snipped>
```

**Comment by dandavison** [comment] 2020-08-15 00:22
Hi @iyerusad, let's get to the bottom of this!

Can you post a plain text small example diff that is causing problems, and a screenshot of delta output when you pipe that diff to delta, using

```
cat example.diff | delta --no-gitconfig --line-numbers
```

For example (you can try this test diff to see if it works for you):

Here is the contents of `example.diff`
```
diff --git a/src/delta.rs b/src/delta.rs
index 33c205cf..d256e77a 100644
--- a/src/delta.rs
+++ b/src/delta.rs
@@ -476,7 +476,7 @@ fn handle_hunk_header_line(
         painter
             .line_numbers_data
             .initialize_hunk(line_numbers, plus_file.to_string());
-    } else {
+    } else if !config.hunk_header_style.is_raw {
         let plus_line_number = line_numbers[line_numbers.len() - 1].0;
         let formatted_plus_line_number = if config.hyperlinks {
             features::hyperlinks::format_osc8_file_hyperlink(
```

and that gives me

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/90301101-cc610a00-de6b-11ea-900f-704dcc23a2e1.png" alt="image" /></td></tr></table>

What do you get if you use my example diff?

**Comment by iyerusad** [comment] 2020-08-16 21:39
Powershell version: 5.1.19041.1

example.diff
--
![image](https://user-images.githubusercontent.com/25647368/90344377-7e1c4a00-dfd6-11ea-9e96-b34ab8b7939b.png)


example2.diff
--
```
diff --git a/vscode/settings.json b/vscode/settings.json
index a5346ba..38bdfb3 100644
--- a/vscode/settings.json
+++ b/vscode/settings.json
@@ -9,6 +9,11 @@
   "workbench.tree.renderIndentGuides": "always",
   "workbench.startupEditor": "newUntitledFile",

+  "files.insertFinalNewline": true, //POSIX-targeted tools want new lines
+  "files.trimFinalNewlines": true,
+  "files.trimTrailingWhitespace": true,
+
+  "diffEditor.ignoreTrimWhitespace": false,
   "editor.renderWhitespace": "boundary",
   "editor.tabSize": 2,
   "editor.insertspaces": true,
@@ -33,6 +38,5 @@
   "peacock.showColorInStatusBar": false,
   "peacock.surpriseMeFromFavoritesOnly": true,

-  "git.autofetch": true,
-  "diffEditor.ignoreTrimWhitespace": false
+  "git.autofetch": true
 }
\ No newline at end of file
```

Get-Content example2.diff | delta --no-gitconfig --line-numbers //Correct line numbers
![image](https://user-images.githubusercontent.com/25647368/90344288-8cb63180-dfd5-11ea-9d6e-45e0bd174600.png)


git show //Incorrect
![image](https://user-images.githubusercontent.com/25647368/90344259-45c83c00-dfd5-11ea-9b47-f1c276c4fd5f.png)

**Comment by dandavison** [comment] 2020-08-17 14:19
Hi @iyerusad, thanks.

1. Does the problem still occur when you do not use `side-by-side`?

2. Can you post the output of `git -c 'core.pager=less' show bc35635`? (That, in my understanding, should be showing exactly the characters that delta is receiving on standard input when invoked by git. So there _ought_ to be no difference in the effects of piping that output into delta, and showing it in delta natively, as long as delta config is the same in both cases.)

3. Is the problem occurring on every commit in your repo? What about other repos? (For example, something public like delta's repo?)

To state what you probably already know: Delta simply receives the standard input that git sends to `core.pager`. So our naive expectation at least, should be that the behavior of delta is the same when invoked by git, versus when sent data on standard input directly (e.g. via a pipe). Delta does use libgit2 to read the user's gitconfig, but that occurs in both cases. Delta doesn't do anything else magical that should cause it to behave differently when invoked by git automatically versus when invoked as a standard command-line application receiving standard input. So really, if you have a situation where you're seeing incorrect line numbers with delta invoked by git, we should be able to capture that diff and reproduce the problem by sending that same diff to delta on standard input.

**Comment by iyerusad** [comment] 2020-08-17 20:51
It appears the setting `hunk-header-style = omit` reproduces this issue:
![image](https://user-images.githubusercontent.com/25647368/90443090-e7649180-e098-11ea-99a4-ad750785d9a5.png)



--
> 1. Does the problem still occur when you do not use side-by-side?

Yes, see below.

> 2. Can you post the output of git -c 'core.pager=less' show bc35635?

I pulled down https://github.com/dandavison/delta, using it to better illustrate. Using [b5f5ca572466dacfc7fada83d8e2f4e52f13f17e](https://github.com/dandavison/delta/commit/b5f5ca572466dacfc7fada83d8e2f4e52f13f17e). The problem persists:
![image](https://user-images.githubusercontent.com/25647368/90439259-80dc7500-e092-11ea-9b82-040e72750c41.png)


> 3. Is the problem occurring on every commit in your repo? What about other repos? (For example, something public like delta's repo?)

Seems to be.

**Comment by dandavison** [comment] 2020-09-09 14:01
> It appears the setting hunk-header-style = omit reproduces this issue:

Hi @iyerusad, thanks for that diagnosis, that was very useful. Sorry this isn't fixed yet, but it is the top priority bug to fix. (looks like same issue as reported in #274 and #319).

**Comment by dandavison** [comment] 2020-09-13 15:28
There's good discussion in #320, which is the same bug. I'm going to close this one in favor of #320 to keep the discussion in one place.

**Closed by dandavison** 2020-09-13 15:28 UTC
