### ISSUE TITLE
Background color issues 

### ISSUE THREAD

**Issue by elbaro** [dandavison/delta#87] opened 2020-01-17 03:37 UTC
![image](https://user-images.githubusercontent.com/1851290/72582348-c16de780-3925-11ea-920f-3a72fce09387.png)

Alacritty 0.4.0, delta 0.0.15

All light themes are broken.
Somehow `--minus-color=xx` does not set to xx, but adds xx.
`--minus-color="#000000"` shows minus diffs with no color.

**Comment by dandavison** [comment] 2020-01-17 03:45
Hi @elbaro, there was another user having issues with alacritty recently. Is this relevant to your problem? https://github.com/dandavison/delta/issues/79#issuecomment-574621788

**Comment by dandavison** [comment] 2020-01-17 03:47
Also, can you confirm that the 24bit color tests linked in the README are passing for you? https://github.com/dandavison/delta#24-bit-color

**Comment by elbaro** [comment] 2020-01-17 03:57
I tried out-of-box iTerm2 on Mac and Kitty on Linux, and the same problem happenes. The 24-bit color test works fine.

**Comment by dandavison** [comment] 2020-01-17 04:14
OK, can you explain a bit more what the problem is exactly? In the screen shot above, it looks like you are using a light theme, but have a dark terminal background. Normally one would only use a light theme with a light terminal background. Sorry if I'm being slow! What exactly is the problem that the screenshot illustrates?

**Comment by elbaro** [comment] 2020-01-17 04:51
Are you saying that to reproduce the screenshot in README.md, one has to use the terminal with #FFFFFF background? Can we have `--ignore-term-color` for 24bit env?


Also this may be a separate issue, but I am seeing a different behavior depending on the color:

git diff | delta --light --minus-color="#000000"
![image](https://user-images.githubusercontent.com/1851290/72585139-40681d80-3930-11ea-9f03-60baa6448e0f.png)

git diff | delta --light --minus-color="#111111"
![image](https://user-images.githubusercontent.com/1851290/72585153-4f4ed000-3930-11ea-9613-7f7ca629dce6.png)

**Comment by dandavison** [comment] 2020-01-17 14:44
> Are you saying that to reproduce the screenshot in README.md, one has to use the terminal with #FFFFFF background?

Yes, that's right, delta only applies the red and green background colors to convey diff information: it doesn't apply a "default" background color to all the text it emits. (Actually the screenshot is with iTerm2 "Material" theme which is some sort of pearl / off-white background).

> Can we have --ignore-term-color for 24bit env to show the exact colors intended?
That could be possible. Am I right in thinking that this feature does not exist in [bat](https://github.com/sharkdp/bat) and that it would be equally appropriate there?

>  I am seeing a different behavior depending on the color:
Can you post some raw output from git diff that is resulting in this behavior? (I.e. as text, not as a screenshot).

**Comment by elbaro** [comment] 2020-01-18 04:21
`bat` is already using the fixed color.
I opened two terminals, one with white theme and one with dark theme.

<img src="https://user-images.githubusercontent.com/1851290/72658358-2cd1bb00-39f3-11ea-9c12-309cda03c28a.png" width="200px">
<img src="https://user-images.githubusercontent.com/1851290/72658360-3529f600-39f3-11ea-808d-73dceeb47d9d.png" width="200px">

In both terminals, `#include` has a color `#f92672`.

Here is delta:

<img src="https://user-images.githubusercontent.com/1851290/72658379-80440900-39f3-11ea-9632-ed719b01d98f.png" width="200px">
<img src="https://user-images.githubusercontent.com/1851290/72658383-8934da80-39f3-11ea-95b9-015baa00991b.png" width="200px">

The red line's foreground color is different (include `#dddddd` vs `#4d4d4c`)
The green line's foreground color is same (if `#a71d5d`)
The other lines' foreground color is same (`#333333`)

```

For the second issue, this can reproduce:
❯ cat diff      
diff --git a/test.cc b/test.cc
index a6e4e99..7cb67e1 100644
--- a/test.cc
+++ b/test.cc
@@ -1,8 +1,9 @@
-#include <stdio.h>
+#include <cstdio>
 
-void main() {
-	if(1) {
+int main() {
+	if(true) {
 		;
 	}
+	retunr 0;
 }

git diff |  delta --light --minus-color="#000000" 
git diff |  delta --light
```

**Comment by dandavison** [comment] 2020-01-28 17:02
Thank you! I can reproduce this; will look into it.

**Comment by dandavison** [comment] 2020-03-03 05:51
@elbaro the color overrun bug you reported (`git diff | delta --light --minus-color="#000000"`) is fixed in master. Thanks very much for reporting that. I know there are one or two remaining issues in this ticket though!

**Comment by dandavison** [comment] 2020-03-03 06:06
Perhaps relevant to the other issues mentioned in here, I've merged a few branches in the last week that I believe improve the ways colors are handled internally, and improve the CLI for specifying colors. So to summarize what delta does and does not do (without any implication as to whether these are bugs or features!):

- Delta allows the syntax highlighting theme specified by `--theme` or the `BAT_THEME` env var to alter foreground colors of code. However, delta does _not_ do this in the removed (red background) sections (to limit the color salad). In red sections you will be getting whatever foreground color is configured in your terminal emulator (This is the cause of one of the issues reported in this ticket).

- Delta applies 4 background colors to certain regions of code in diffs. Some regions of code do not receive a background color. 

All color command line options can be specified either as explicit 24-bit RGBs, or as one of the 256 ANSI codes (see `--help`). With the recent changes, delta will automatically choose an 8-bit approximation to any 24-bit colors when it detects an 8-bit color terminal environment. 

 The following text is now printed out at the end of the `--help` text:

```
Colors
------

All delta color options work the same way. There are two ways to specify a color:

1. RGB hex code

   An example of passing an RGB hex code is:
   --file-color="#0e7c0e"

2. ANSI color name

   There are 8 ANSI color names:
   black, red, green, yellow, blue, magenta, cyan, white.

   In addition, all of them have a bright form:
   bright-black, bright-red, bright-green, bright-yellow, bright-blue, bright-magenta, bright-cyan, bright-white

   An example is:
   --file-color="green"

   Unlike RGB hex codes, ANSI color names are just names: you can choose the exact color that each
   name corresponds to in the settings of your terminal application (the application you use to run
   command line programs). This means that if you use ANSI color names, and you change the color
   theme used by your terminal, then delta's colors will respond automatically, without needing to
   change the delta command line.

   "purple" is accepted as a synonym for "magenta". Color names and codes are case-insensitive.
```

**Comment by dandavison** [comment] 2020-05-29 02:08
@elbaro I believe all the issues you described here  are finally fixed in `master`. Please see the write-up in #205.

**Closed by dandavison** 2020-05-29 02:08 UTC
