### ISSUE TITLE
Color not matching between `delta` and `git diff`

### ISSUE THREAD

**Issue by lfilho** [dandavison/delta#678] opened 2021-08-07 22:52 UTC
Hi team, thanks a lot for the great tool!

I'm just trying it for the first time and adding it to my dotfiles, but I can't get the syntax theme to look like the example present in the `delta --show-syntax-themes --dark` command. When running an actual `git diff` command the colors get too dark/low contrast so it's a bit too hard to see comfortably. Screenshots below.

Details:
- iTerm 3.4.8
- delta 0.8.3
- bat 0.18.2
- using `gruvbox-dark` color preset for iTerm

My (relevant parts of) .gitconfig:

```
[diff]
  # Git diff will use (i)ndex, (w)ork tree, (c)ommit and (o)bject
  # instead of a/b/c/d as prefixes for patches
  mnemonicprefix = true
  algorithm = patience
  compactionHeuristic = true
  colorMoved = default
[pager]
  diff = "delta"
  show = "delta"
  reflog = "delta"
  show = "delta"
[delta]
  syntax-theme = Monokai Extended
  navigate = true
  side-by-side = true
  line-numbers = true
[interactive]
  diffFilter = delta --color-only
```

### `git --no-pager diff`

![image](https://user-images.githubusercontent.com/282756/128615631-45c12e48-e617-429b-9376-3bd23a82b8f5.png)

### `delta --show-syntax-themes --dark` (with Monokai Extended showing)

Note shades of red and green:
![image](https://user-images.githubusercontent.com/282756/128615668-1e6ee052-dbff-4f7d-a4c9-7b2170fa22d9.png)

### `git diff`(using delta)

Note how it doesn't look like the colors of the Monokai Extended example above (what I wanted)
![image](https://user-images.githubusercontent.com/282756/128615681-ad5cb3cd-5b46-4120-a8b5-ac1c0c18af75.png)

I tried selecting gruvbox-dark as the syntax-theme but the same problem happens.

The only other reference to any color-related configs in my gitconfig is this:

```
[color]
  ui = true
[color "branch"]
  current = yellow reverse
  local = yellow
  remote = green
```

Am I missing? Thanks

**Comment by Kr1ss-XD** [comment] 2021-08-20 22:48
Hi @lfilho, welcome to the delta user club !

I think you're confusing the syntax highlighting _theme_ with the color _style_ here.

The former has to do with the actual text colors (for example in your 2nd screenshot, the `fn` and `let` keywords being light blue). The concept of these themes stems from the `bat` [project](https://github.com/sharkdp/bat/tree/master/assets/themes), and in context with delta they are defined with the `delta.syntax-theme` option in the git configuration.

`delta --show-syntax-themes` is meant to demonstrate only the available syntax-highlighting "themes", using a default delta color "style". Actually, when you look at the output of that command and focus on the diff-highlight (=background) colors, you should notice that they aren't different from one example to another.

The background colors, on the other hand, are part of delta's general "[color style](https://github.com/dandavison/delta#choosing-colors-styles)" concept, which uses quite a number of settings ending with `-style`. For example, the diff-highlight colors can be defined with `minus-style`, `minus-emph-style`, `plus-style` and `plus-emph-style`.

There are so many more `-style` options you can use; also, there are the options that end with `-format`, which define details like how many room line numbers should have, or how the commit headers should look like, just to name some examples. In my opinion one of delta's greatest features is that you can configure so many details to your personal liking. I recommend to study the according paragraph in `README.md`, or especially the output of `delta --help`.

It's worth mentioning that delta comes with a set preconfigured [styles](https://github.com/dandavison/delta/blob/master/themes.gitconfig), which you can use by adding the following to your `.gitconfig` : 

```gitconfig
[include]
	path		= /etc/delta/themes.gitconfig
[delta]
	features	= <name_of_style>
```

Assuming the path to the file is `/etc/delta/themes.gitconfig` - otherwise it needs to be adjusted of course.

Here's a [list](https://github.com/dandavison/delta/pulls?q=is%3Apr+is%3Aclosed+in%3Atitle+add+theme) of pull requests adding configurations to `themes.gitconfig` - each of them should contain a screenshot, so you can pick which one(s) you like best.

**Comment by dandavison** [comment] 2021-08-21 04:25
Hi @lfilho, and thanks for that @Kr1ss-XD. So if we had to summarize what @Kr1ss-XD is saying very briefly:

"syntax theme" = foreground text colors
"theme" = background colors + syntax-theme + other decorations (boxes etc)

@lfilho what you wrote made me realize that the output of `--show-syntax-themes` is confusing. I've changed it to say "Syntax theme" rather than simply "Theme".

So it sounds like what you're looking for is the brighter more contrasty background  colors, and as @Kr1ss-XD says -- those are the `*-style` settings. I can't look right now to see why the background colors differ between `show-syntax-themes` and the defaults you're seeing in your diff but it would be helpful if I or someone else could add that info to this discussion.

I'll close the issue since it looks like there's not a bug here, but please feel free to carry on discussing while you get your delta config sorted out to your liking.

**Closed by dandavison** 2021-08-21 04:25 UTC

**Comment by lfilho** [comment] 2021-09-06 21:18
Sorry for the delay here, I was moving cities and busy with everything that goes with it :) 

Thank you both for the detailed and helpful comments, appreciate it!

So if I got it right, the examples shown in `delta --show-syntax-themes` uses a fixed/hardcoded set of styles, not the styles I have currently configured. Is that correct? So I guess that's my suggestion here: to make the styles in that output follow whatever you have configured in your delta/bat so you can see how it would like for real.

A second suggestion would be to have a page or command showing the available `themes` that one could choose from (similar to the `--show-syntax-themes` above, but for `themes`) -- the list of PRs you provided is great but incomplete (not all have screenshots), and ideally we would be able to see the themes in the command line itself, without having to open github and browsing around.

I'll fiddle with it all now then, thanks again for your thoughtful answer

**Comment by Kr1ss-XD** [comment] 2021-09-15 15:47
Hi @lfilho !

You're correct in that `delta --show-syntax-themes` demonstrates a predefined list of what `bat` calls `themes`. Basically, the output is that of `bat --list-themes`, but with the example converted to a diff and with applied diff highlighting (<=> background colors) for demonstration.

>the list of PRs you provided is great but incomplete (not all have screenshots)

I can't find one that doesn't have one ?

>ideally we would be able to see the themes in the command line itself, without having to open github and browsing around.

Is `delta --show-themes` what you're imagining ?
