### ISSUE TITLE
🚀 Is it possible to see the exceeded line in side-by-side feature

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/delta#314] opened 2020-09-02 22:10 UTC
I am using `side-by-side` as feature. I realize when the terminal width is small and there is a long line I see `→` at the end of the exceeding lines.

Ex:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/18537398/92042143-393c3580-ed82-11ea-86bb-b96a50bddd7a.png">

[Q] Is it possible to see the remaining part of the line on the next line?

**Comment by dandavison** [comment] 2020-09-02 22:20
Hi @avatar-lavventura, this is a duplicate of https://github.com/dandavison/delta/issues/299. There are some suggestions for workarounds in https://github.com/dandavison/delta/issues/299#issuecomment-681975253

**Closed** 2020-09-02 22:29 UTC
