### ISSUE TITLE
🐛 Wrong colors in windows 10

### ISSUE THREAD

**Issue by DomantasJ** [dandavison/delta#600] opened 2021-05-12 10:21 UTC
I'm not sure if something needs more configuration, but the default config I copied from readme gave me a horribly looking gray background. Trying to change colors did not end with results I expected.

Less version: 581.2
Delta version: 0.7.1
Shell: powershell
Terminal emulator: Cmder

Git config:

```
[core]
    pager = delta
[delta]
    plus-style = "syntax #00ff00"
    minus-style = "syntax #ff0000"
    syntax-theme = Monokai Extended
    navigate = true
    line-numbers = true
[interactive]
    diffFilter = delta --color-only
```

Raw diff (without delta):

![image](https://user-images.githubusercontent.com/41150975/117956291-9466f480-b321-11eb-976e-94c7622d03e8.png)

Diff with delta (powershell, terminal emulator is cmder):

![image](https://user-images.githubusercontent.com/41150975/117956453-b82a3a80-b321-11eb-86d1-8b927b4c0633.png)

Same diff in the default terminal emulator for powershell:

![image](https://user-images.githubusercontent.com/41150975/117956573-d8f29000-b321-11eb-87ea-be0afaefa40b.png)

The output from `delta --show-syntax-themes` seems reasonable:

![image](https://user-images.githubusercontent.com/41150975/117962446-e743aa80-b327-11eb-90be-d0d707a9715c.png)

**Comment by dandavison** [comment] 2021-05-12 11:09
Hello @DomantasJ. I think your terminal emulator is not supporting 24-bit color. Can you try setting

```gitconfig
[core]
    pager = delta  --24-bit-color=never
[interactive]
    diffFilter = delta --color-only --24-bit-color=never
```

Also, to check whether your terminal emulator supports 24-bit-color there are scripts you can run that print out colors. There are some linked in the delta README: https://github.com/dandavison/delta#24-bit-color-truecolor

**Comment by DomantasJ** [comment] 2021-05-13 14:00
That setting did not change anything, everything looks exactly the same.

I found that Cmder does not support 24-bit color, but powershell and cmd do. I can print out a nice looking rainbow in powershell, but output from delta still looks bad. And I still have no idea how to get anything close to what `delta --show-syntax-styles` prints.

**Comment by dandavison** [comment] 2021-05-13 14:39
Hi, OK, in that case I think the problem is with less. I know you specified that you've got a recent less version installed, but is it possible that the less being picked up by delta is in fact an older version? To test that, can you run delta with `--paging=never`?

As a workaround you could possible also try

```gitconfig
[core]
    pager = delta --paging=never | /absolute/path/to/less_v581.2
```

I'm sorry, what I'd really like is to have a good help page for Windows users summarising all the problems that come up and solutions (in a nutshell; make sure your terminal emulator supports 24-bit coplor and make sure thatg the less beingpicked up by delta really is the one you hope it is). If you search the issue history you'll see that there are lots of people who've had similar problems to what you're having, but you'll also see that digesting all the conversations in those tickets is rather hard!

**Comment by DomantasJ** [comment] 2021-05-17 14:03
What does delta do when there's no `less` installed? I tried to remove the one I have installed and I got exactly the same output but without paging. I don't have any other `less` in my path except for the v581.2 one.

`pager = delta --paging=never` works in cmder (gives correct colors and does no paging), but breaks completely in powershell:

![image](https://user-images.githubusercontent.com/41150975/118501663-a38adf80-b731-11eb-9307-fb4165ec7603.png)

Piping to `less` explicitly fixes colors in cmder, but breaks non-ascii text:

![image](https://user-images.githubusercontent.com/41150975/118501521-7b02e580-b731-11eb-8be5-7c564e4ea797.png)

![image](https://user-images.githubusercontent.com/41150975/118501597-90780f80-b731-11eb-8c5b-77ff51aa33d4.png)

**Comment by dandavison** [comment] 2021-05-17 14:30
Hi @DomantasJ, I'm sorry this is being such a pain! Could you run this shell script and post a screenshot of the output?

https://github.com/dandavison/delta/blob/master/etc/bin/diagnostics

**Comment by pilif-pilif** [comment] 2021-05-20 14:11
Hi, I installed today Delta and had the same problem. I ended reinstalling the version of "less" which comes with my "Git" Version - less 563 and it solved this color problem.

**Comment by dandavison** [comment] 2021-08-22 02:43
Hi @DomantasJ, any luck here? I don't have a document giving known-good combinations of terminal emulators etc for Window unfortunately, but the problem here is some combination of less versions and windows terminal emulators not supporting 24-bit color and/or certain unicode characters. I'll close this for now as it has gone dormant.

**Closed by dandavison** 2021-08-22 02:43 UTC
