### ISSUE TITLE
🐛 Missing last character in wrapped line

### ISSUE THREAD

**Issue by antoyo** [dandavison/delta#830] opened 2021-12-06 21:57 UTC
Hi.
To reproduce this use, with delta 0.11, add the following code in a file:
```rust
pub fn bla() -> crate::Result<()> {
    // NOTE: write the DAT first because some tests (like test_data_for_some_reasons_not_now) have
    Ok(())
}
```
Add it to a git repo.
Then `git lop -p` will show it, with the missing letter `e` in the word `have`:
```
    Initial commit


added: main.rs

───┐
1: │
───┘
│    │                                                                                 │ 1  │pub fn bla() -> crate::Result<()> {
│    │                                                                                 │ 2  │    // NOTE: write the DAT first because some tests (like test_data_for_some_rea
│    │                                                                                 │    │                                                              …sons_not_now) hav
│    │                                                                                 │ 3  │    Ok(())
│    │                                                                                 │ 4  │}
```
My terminal is Alacritty in case this matters.
Thanks to fix this issue.

**Comment by dandavison** [comment] 2021-12-06 22:04
Hi @antoyo, how many columns wide is your terminal (you can use `tput cols` to query) when you see this incorrect output? If you change the width, do you still see incorrect output?

**Comment by antoyo** [comment] 2021-12-13 16:34
`tput cols` return `174`.

When changing the width of the terminal window, the output can be even more incorrect:
```
───┐
1: │
───┘
│    │                              │ 1  │pub fn bla() -> crate::Result
│    │                              │    │                       …<()>
│    │                              │ 2  │    // NOTE: write the DAT fi
│    │                              │    │rst because some tests (like
│    │                              │    │test_data_for_some_reasons_no
│    │                              │ 3  │    Ok(())
│    │                              │ 4  │}
```
That makes me wonder if it is because the algorithm won't cut the word `test_data_for_some_reasons_not_now` because it has underscores in it.

**Comment by dandavison** [comment] 2021-12-13 17:09
Hi @antoyo, OK, I haven't been able to reproduce this yet. (Screenshot below). Could you post the output of
```
env | grep -iE '(less|pager)'
```
I'm wondering if this is related to `less` adding a status column (`-J`). Note that delta `width` argument allows you to specify an offset. Can you experiment with that (e.g. `width = -1`)?

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/145856154-b4a5dadd-eef3-4e06-ac13-a867724d3f55.png" alt="image" /></td></tr></table>

**Comment by antoyo** [comment] 2021-12-13 17:49
The output of that command is empty.
Using `width=-1` fixes the issue.

**Comment by dandavison** [comment] 2021-12-13 18:44
OK, great. It sounds like something is causing `less` to insert an extra column on the left, resulting in delta thinking that it has one more column available to it than it actually has. I'll close this now since you have a fix.

**Closed by dandavison** 2021-12-13 18:44 UTC
