### ISSUE TITLE
🚀 Use light/dark theme base on terminal theme or system variable.

### ISSUE THREAD

**Issue by tshu-w** [dandavison/delta#447] opened 2020-12-15 06:08 UTC
Hi, I have set my terminal to auto change themes based on macOS appearance. It would be much appreciated if delta can use light/dark theme base on terminal theme or system variable.

**Comment by lourenci** [comment] 2020-12-17 16:17
I second that. I'm struggling with the same issue. 

I don't care about the `delta` theme at all, I wish `delta` could just alternate between `--light` and `--dark` colors according to the terminal colors automatically.

Out of the curiosity, what terminal emulator are you using @tshu-w? Does it support this out-of-the-box?

Thank you.

**Comment by tshu-w** [comment] 2020-12-17 16:49
@lourenci Hi, I'm using iTerm2 on macOS, unlike the terminal that comes with the system, it requires a [script](https://gist.github.com/jamesmacfie/2061023e5365e8b6bfbbc20792ac90f8) to make the automatic switch possible.

**Comment by dandavison** [comment] 2020-12-17 17:48
Hi @tshu-w and @lourenci, yes let's figure out a good way to do this. What do you think of this proposal:

- There are two parts to this: (1) detecting the relevant system state (e.g. OS dark mode, or current terminal color theme etc) and (2) getting delta to respond to the relevant system state.

- I suggest we address those separately. Specifically, I suggest that we say that (1) is not Delta's responsibility. Instead, Delta will expose an environment variable named `DELTA_FEATURES`. This environment variable does exactly the same thing as the existing `--features` flag. (see [custom features](https://github.com/dandavison/delta#custom-features) and [`--help` output](https://github.com/dandavison/delta#full---help-output))

- Thus it is the user's responsibility to populate the `DELTA_FEATURES` environment variable with the names of the custom features they want to be active, in response to changes in their system state. One way to do this might be to use shell prompt code (i.e. shell code that is executed every time the prompt is displayed).

- So, for example, one might define custom features something like below, and then arrange for `DELTA_FEATURES` to contain either `"my-light-mode"` or `"my-dark-mode"` as appropriate.
```gitconfig
[delta "my-light-mode"]
    light = true
    file-style = magenta # or whatever other settings you want; this is just an example

[delta "my-dark-mode"]
    dark = true
    file-style = green # or whatever other settings you want; this is just an example
```

If you're able to [build delta from source](https://github.com/dandavison/delta#build-delta-from-source) then you can play around with this now as I've added support for the `DELTA_FEATURES` env var. cc @ulwlu ref https://github.com/dandavison/delta/pull/340#issuecomment-744257639

If this seems like a good way forward then let's put together a concrete example of doing this with a particular OS/terminal emulator/shell combination.

**Comment by dandavison** [comment] 2020-12-18 16:19
@tshu-w @lourenci here's a proof-of-principle that uses [iTerm2 proprietary escape codes](https://iterm2.com/documentation-escape-codes.html) and zsh's preexec hook. Unfortunately the iterm2 escape codes do not work in tmux.

Instructions:

1. Set up Delta features for your light and dark modes:
    ```gitconfig
    [delta "my-light-mode"]
        light = true
        syntax-theme = GitHub

    [delta "my-dark-mode"]
        dark = true
        syntax-theme = Dracula
    ```

2. Arrange for the `DELTA_FEATURES` env var to be populated correctly according to the current terminal background color,  before running any command (This is for `zsh`; in bash one can use `PROMPT_COMMAND` which runs before displaying the prompt). 
    ```zsh
    __dan_preexec_function () {
        export DELTA_FEATURES="my-$(iterm2-get-light-or-dark-bg)-mode"
    }
    typeset -ag preexec_functions;
    preexec_functions=( __dan_preexec_function ${preexec_functions[@]} )
    ```

3. Put the python script below on your `$PATH` with the name `iterm2-get-light-or-dark-bg` and make it executable.

Now run `exec zsh` to reload `zsh` config and Delta will automatically switch between your light/dark modes according to the relative luminance value of the background color used by your iTerm2 color theme.

```python
#!/usr/bin/env python
import subprocess
import sys

def gamma_correct(rgb: int) -> float:
    rgb = rgb / 255
    return rgb / 12.92 if rgb <= 0.03928 else ((rgb + 0.055) / 1.055) ** 2.4


def luminance(r: int, g: int, b: int) -> float:
    """
    https://www.w3.org/TR/WCAG20/#relativeluminancedef
    """
    r, g, b = map(gamma_correct, [r, g, b])
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

# https://iterm2.com/documentation-escape-codes.html
cmd = "read -s -N 26 -p $'\x1b]4;-2;?\x07' RESPONSE; echo \"$RESPONSE\""

response = subprocess.check_output(["bash", "-c", cmd]).strip().decode('utf-8')
r, g, b = map(lambda hex: int(hex[:2], 16), response.split(":")[1].split('/'))

sys.stdout.write("light\n" if luminance(r, g, b) > 0.5 else "dark\n")
```

**Comment by ulwlu** [comment] 2020-12-18 16:27
Hi, I agree with dandavison that this is not delta's responsibility, but I feel not a few people want this. 
I knew this library can solve this issue.

https://github.com/dalance/termbg

If we'll approach as delta side will solve this, I will fix.

**Comment by dandavison** [comment] 2020-12-18 16:36
@ulwlu oh, that library looks perfect. I am absolutely happy for us to build in background color detection to Delta. You're right: that would be a much better solution. Terminal color detection is important enough for delta to do it. And I see it has some tmux support... the code I posted above doesn't work in tmux.

**Comment by ulwlu** [comment] 2020-12-18 16:39
Yes it works in tmux. There are many informations about this library in Japanese articles, so I'm going to give it a try in a few days!

**Comment by dandavison** [comment] 2020-12-18 22:12
> Yes it works in tmux. There are many informations about this library in Japanese articles, so I'm going to give it a try in a few days!

Ok, sounds great -- I'll leave this one for you to work on.

**Comment by dandavison** [comment] 2020-12-22 17:39
I've been trying to think about how we want this to work ultimately. Basically, `termbg` (if it works as we hope) is going to give  us two states: light mode and dark mode. Initially, I think we can just have that switch between delta's existing `--light` and `--dark` settings.

Ultimately, I think it would be nice if users could have two features defined in their gitconfig, one for their light mode settings, and one for their dark mode settings. These would contain the `syntax-theme` and colors, etc. I'm not sure whether those feature names should be fixed, e.g. `[delta "light"]` and `[delta "dark"]` or whether users should be able to specify the name of the custom feature that holds their light-mode and dark-mode settings.

A related issue is that the code for `light` and `dark` should probably be refactored to use the "builtin feature" pattern (src`/features/*`).

**Comment by tshu-w** [comment] 2021-01-09 11:23
@dandavison @ulwlu Thank you for your efforts, I've been a bit busy recently. Although the solution provided by @dandavison is sufficient, I agree that it would be great for delta to have built-in color detection, so I will leave this issue open.

**Comment by sscherfke** [comment] 2021-01-21 19:40
>  Basically, `termbg` (if it works as we hope) is going to give us two states: light mode and dark mode.

I have a custom script to set/get/toggle darkmode states on different OS’.  Maybe delta could expose an environment variable (e.g., `DELTA_TERMBG_CMD="dm get"`) that can be used if/when `termbg` is not available/does not work as expected?

**Comment by ulwlu** [comment] 2021-01-25 02:46
@sscherf@ss
oh sorry for repling late. As my status said I'm currently quite busy with my job until March.
If you can create PR, it would be better.

**Comment by skyfaller** [comment] 2021-03-06 19:58
bat "solved" this by providing an "ansi" theme, replacing ansi-dark and ansi-light, which automatically switches colors to work in either a dark or light theme. https://github.com/sharkdp/bat/issues/1104

Could delta do the same?

**Comment by dandavison** [comment] 2021-03-28 00:10
Hi @skyfaller I'm sorry, I was on the verge of replying to this 3 weeks ago when you said it and then somehow didn't! What I was going to say is thanks, and you prompted me to update delta to bat's latest themes, so `ansi` will be available in delta (and ansi-light and ansi-dark will be gone), since delta follows bat here. However, delta users also (mostly) specify background colors for the different sorts of highlighting of plus and minus lines, and this is typically done with 256 colors or 24-bit colors, and so the question of automated choice between two modes of those colors would still be unsolved, as I'm understanding things.

**Comment by skyfaller** [comment] 2021-03-28 00:30
@dandavison Thank you! It doesn't solve the problem for people who want more advanced themes, no, but for people who just want legible text for now, the "ansi" theme is a fine workaround. I look forward to the next release!

Here's what I did to "solve" the problem for myself in the meantime, on Gnome with [fish shell](https://fishshell.com/) using [sd](https://github.com/chmln/sd).

I made a fish function that detects my Gnome theme and uses that to change my .gitconfig to my desired delta theme:
```fish
function theme-delta --description 'Set delta theme based on gtk-theme'
  switch (gsettings get org.gnome.desktop.interface gtk-theme)
  case "'Pop'"
    sd '^\tsyntax-theme = .*$' '\tsyntax-theme = gruvbox' ~/.gitconfig
  case "'Adwaita'"
    sd '^\tsyntax-theme = .*$' '\tsyntax-theme = GitHub' ~/.gitconfig
  case "'Pop-dark'"
    sd '^\tsyntax-theme = .*$' '\tsyntax-theme = Monokai Extended' ~/.gitconfig
  case '*'
    echo "error: unidentified GTK theme"
  end
end
```
Then I use the [Night Theme Switcher GNOME Shell extension](https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension/) to run that fish function (and similar functions for Alacritty and bat) at the same time as it changes my theme between light and dark, like so:
`/usr/bin/fish -c 'theme-bat; theme-alacritty; theme-delta'`

I'm very interested to see how you finally solve this, termbg looks cool!

**Comment by dandavison** [comment] 2021-03-28 00:39
Cool, thanks, that's a lot of helpful links and example code! (And I hadn't come across `sd`, I'll definitely look into that.)

**Comment by jtroo** [comment] 2021-04-29 19:38
I just tried out the `ansi` theme in the latest master (1b3bd2877a3ba97a2fa10a328610edc945e993f4) and it doesn't behave as expected. Works on light themes, but not dark themes. I think the default text color is set to black, when it actually should be left uncolored.

**Comment by dandavison** [comment] 2021-04-29 21:13
Thanks very much you @jtroo. Should be fixed in https://github.com/dandavison/delta/pull/581. Any chance you could confirm that's behaving as expected for you?

**Comment by dandavison** [comment] 2021-04-29 21:25
> Thanks very much @jtroo. Should be fixed in #581. Any chance you could confirm that's behaving as expected for you?

Ah I'm sorry, ignore that, there's more work to be done on that branch. I'll ping here again when I've merged that branch to master.

**Comment by jtroo** [comment] 2021-04-29 21:41
I built and tested off of that branch. Works as expected now :)

**Comment by dandavison** [comment] 2021-04-30 02:19
> I built and tested off of that branch. Works as expected now :)

Thanks @jtroo! There were just some fairly superficial test failures; in master now.

**Comment by lourenci** [comment] 2021-05-20 12:40
Just a feedback: `ansi` is not working for me on `HEAD`.

My config:
```
[delta]
  navigate = true
  syntax-theme = ansi
```

Output (light terminal):
<img width="918" alt="image" src="https://user-images.githubusercontent.com/2339362/118979880-51bfa080-b94f-11eb-962c-db5ef8b6425b.png">

**Comment by jtroo** [comment] 2021-05-20 21:15
@lourenci that looks to be behaving correct to me. The issue is that the green/red bgs are too dark. You may want to adjust your terminal colours, choose a custom green/red for delta, or choose custom text output (as opposed to syntax highlighted).

**Comment by dandavison** [comment] 2021-05-20 21:53
Actually, I think there might be an even easier fix. @lourenci, I think you need to add `light = true`:

```gitconfig
[delta]
  light = true
  navigate = true
  syntax-theme = ansi
```

By default, delta assumes your terminal background is dark, since I think most people use dark (but I'm with you, mine is light too).

**Comment by dandavison** [comment] 2021-05-20 21:55
For the record, I'll point out that `syntax-theme` only affects _foreground_ colors (syntax highlighting). Background colors are not affected at all by setting `syntax-theme`; they are affected by things like `plus-style` etc.

**Comment by chtenb** [comment] 2022-03-30 07:26
> Hi @skyfaller I'm sorry, I was on the verge of replying to this 3 weeks ago when you said it and then somehow didn't! What I was going to say is thanks, and you prompted me to update delta to bat's latest themes, so `ansi` will be available in delta (and ansi-light and ansi-dark will be gone), since delta follows bat here. However, delta users also (mostly) specify background colors for the different sorts of highlighting of plus and minus lines, and this is typically done with 256 colors or 24-bit colors, and so the question of automated choice between two modes of those colors would still be unsolved, as I'm understanding things.

Yes exactly. I use ansi compatible colors for syntax highlighting but still need to revert to 24-bit colors for background highlighting the plus and minus lines. So using ansi syntax is not a full workaround.

What is the status of this issue? Has the termbg support been released yet?

**Comment by chtenb** [comment] 2022-03-30 07:29
I also want to comment on the `DELTA_FEATURES` approach. I'm afraid that this is not going to solve all use cases. I'm using VSCode and my theme switches based on system settings. I'm afraid that 

1. there is no way to hook into that change and set environment variables in this situation
2. changing environment variables will not affect open terminals

**Comment by floriankisser** [comment] 2022-03-30 07:33
I tried termbg, but it needs stdin and stdin is already in use for the pipe.

**Comment by chtenb** [comment] 2022-03-31 08:15
> @chtenb right, that's true. But you can use some suitable mutable state such as a file on disk, and create a wrapper script around delta that looks at the file to see whether you're in light/dark mode, and invokes delta accordingly.

That is true, but I'm not sure how I would have the filesystem mutated based on my VSCode theme. I'm sure I could hack _something_ together like inspecting the VSCode config, but a generic solution that is able to inspect the background of the terminal sounds so much more clean and easy to use for everyone. But it sounds like that problem is not solvable in a generic way for every terminal?

> @floriankisser thanks, yes, I looked into `termbg` also and came to that conclusion. Unless there's some trick we're missing, it seems to be a non-starter: delta uses stdin to receive its input.

It seems that VSCode is not supported so I wouldn't benefit from termbg.

**Comment by chtenb** [comment] 2022-04-15 21:12
I explored solving this problem from a different angle: by only using ansi colors. I used the basic ansi colors (0-15 for syntax highlighting and repurposed some of the extended ansi colors (16-255) as background for colored lines as follows

```ini
[delta]
    syntax-theme = terminal-ansi16
    features = zebra-ansi

[delta "zebra-ansi"]
    minus-style = syntax 52
    minus-emph-style = syntax 88
    plus-style = syntax 22
    plus-emph-style = syntax 28

    map-styles = \
       bold purple => syntax 53, \
       bold blue => syntax 17, \
       bold cyan => syntax 23, \
       bold yellow => syntax 58

    zero-style = syntax
    whitespace-error-style = "#aaaaaa"
```

The syntax theme I used is a custom bat theme [terminal-ansi16](https://github.com/chtenb/ansi16/blob/main/terminal-ansi16.tmTheme). It only uses ansi colors just like the bat ansi theme, but it's better than the default included ansi theme imho :).


If your terminal supports customization of the entire range of ansi colors (0-255) and is able to switch themes based on your system theme, then you can leverage both these things to achieve an adaptive experience. Here is a video that shows a diff while I switch my system darkmode setting (on Windows 10) using wezterm as my terminal.

https://user-images.githubusercontent.com/1030961/163631100-50241cdb-eb00-4f93-9736-8cfadfbcea5b.mp4

For the record, [this is the wezterm configuration that I used.](https://github.com/chtenb/dotfiles/blob/84d1b75b69e7c44c96ce8a284c058fc869d3529e/wezterm.lua) It's a bit hacky with all the hardcoded colors imho, but it works.

Furthermore, I have flux installed and configured to switch darkmode on/off based on the time of day.

**Comment by seansfkelley** [comment] 2022-09-07 13:34
If you're on a Mac, you can `defaults read` the current theme and use that to configure delta features at runtime:

```gitconfig
[core]
  pager = delta --features "$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo dark-mode || echo light-mode)"

[delta "light-mode"]
  light = true
  syntax-theme = GitHub

[delta "dark-mode"]
  light = false
  syntax-theme = Visual Studio Dark+
```

This precludes the need to wire up something to listen to changes to the system theme and to write that to some environment variable somewhere.

**Comment by eproxus** [comment] 2023-02-15 12:08
@seansfkelley Thanks a lot for that snippet! I had to add the following for it to work for `git add --patch` too:
```ini
[interactive]
    diffFilter = delta --color-only --features "$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo dark-mode || echo light-mode)"
```

**Comment by anu-anand-premji** [comment] 2023-03-31 12:14
This is what works for me on GNOME (Ubuntu 22.10).
For context, I use the default dark/light on Ubuntu and everything including terminal theme switches as I switch the system-wide dark/light theme. 

The below settings checks the system theme and if it sees "dark" in the theme name, delta will use the dark-theme; otherwise light-theme. Had to use `case` instead of a more readable `if` statement due to the command needing to be POSIX compliant. 

```gitconfig
[core]
    pager  = LESS=-R delta --features "$(case "$(gsettings get org.gnome.desktop.interface gtk-theme)" in *"dark"*) echo "dark-theme" ;; *) echo "light-theme" ;; esac)"

[delta]
    syntax-theme = none
    side-by-side = true
    line-numbers = true

[delta "dark-theme"]
    minus-style = syntax "#330f0f"
    minus-emph-style = syntax "#4f1917"
    plus-style = syntax "#0e2f19"
    plus-emph-style = syntax "#174525"
    map-styles = \
       bold purple => syntax "#330f29", \
       bold blue => syntax "#271344", \
       bold cyan => syntax "#0d3531", \
       bold yellow => syntax "#222f14"
    zero-style = syntax
    whitespace-error-style = "#aaaaaa"

[delta "light-theme"]
    minus-style = syntax "#fbdada"
    minus-emph-style = syntax "#f6b6b6"
    plus-style = syntax "#d6ffd6"
    plus-emph-style = syntax "#adffad"
    map-styles = \
       bold purple => syntax "#feecf7", \
       bold blue => syntax "#e5dff6", \
       bold cyan => syntax "#d8fdf6", \
       bold yellow => syntax "#f4ffe0"
    zero-style = syntax
    whitespace-error-style = "#aaaaaa"
```

**Comment by texastoland** [comment] 2023-05-17 00:49
FWIW it can be simplified if you don't care which light/dark theme:

```gitconfig
[core]
pager = git delta

[interactive]
diffFilter = git delta --color-only

[alias]
delta = delta $(defaults read -g AppleInterfaceStyle &>/dev/null || echo --light)
```

**Comment by aykevl** [comment] 2023-07-29 17:56
I did some investigating in https://github.com/dandavison/delta/pull/1493#issuecomment-1656805343 and came to the conclusion that reading the terminal background color using the xterm trick is not reliably possible when used together with less, because of a race condition between less and delta (see that comment for details). I guess @dandavison came to the same conclusion.

(stdin is not actually the issue, we can use stderr for read and write: the real issue is a race condition).

However, it would be possible to implement support for `$COLORFGBG` which is supported in a number of terminals. The main downside of that is that it is an environment variable which doesn't reflect dynamic changes to dark mode, but at least it is correct at the time the terminal starts (which may be more often than just assuming a dark background).

**Comment by dandavison** [comment] 2024-03-12 12:38
Hi all, I'm about to merge a solution for this issue contributed by @bash in https://github.com/dandavison/delta/pull/1615. I'd really appreciate it if you could test out that branch and confirm it's working for you.

**Comment by texastoland** [comment] 2024-03-15 01:50
WFM with Lazygit integration in latest macOS on Intel ✅

**Comment by dandavison** [comment] 2024-03-16 14:58
Thanks all. This is now fixed and released in delta 0.17.0  thanks to @bash's work in https://github.com/dandavison/delta/pull/1615.

(tmux users: we need to detach and reattach in order for delta to respond to a change in terminal background color. If anyone has solutions there please let this thread know)

**Closed by dandavison** 2024-03-16 14:58 UTC

**Comment by texastoland** [comment] 2024-03-24 19:12
> WFM with Lazygit integration in latest macOS on Intel ✅

I must have been using my old config. `delta --detect-dark-light always` (or `auto`) is always dark for me.

**Comment by bash** [comment] 2024-03-25 12:17
@texastoland Yepp, unfortunately automatic detection does not work inside of lazygit, see also https://github.com/dandavison/delta/issues/1664.

**Comment by texastoland** [comment] 2024-03-25 12:45
Informative thread thank you 🙏🏼
