### ISSUE TITLE
🐛Handle diff.submodule log

### ISSUE THREAD

**Issue by fdcds** [dandavison/delta#60] opened 2019-11-22 10:43 UTC
It appears that delta has some trouble finding the end of a hunk:
```diff
--- a   2019-11-27 12:06:18.472973416 +0100
+++ b   2019-11-27 12:06:23.992967043 +0100
@@ -1,7 +1,7 @@
 x
 y
 z
-a
+b
 z
 y
 x
Submodule x/y/z contains untracked content
```

Is displayed (roughly) as:
```
a
---------------------------------------
-----|
 ... |
-----|
1
 x
 y
 z
-a
+b
 z
 y
 x
 ubmodule x/y/z contains untracked content
```

Note how "Submodule"'s first character gets removed by delta.

Using delta 0.0.14.

**Comment by fdcds** [comment] 2019-11-22 10:47
Proposal how to fix this: You know that a hunk in unified diff starts with `^@@`. From there to the first `^[-+]` count the number of lines. From the last `^[-+]`, use just as many lines as the trailing context of the hunk. If you find a line that does not match `^ `, you have reached the end of the hunk, independently of how many lines you already read, and should stop parsing hunk context immediately.

**Comment by fdcds** [comment] 2019-12-16 13:20
Somehow this seems to not have worked. With `git config --global diff.submodule log` `git diff` outputs:
```
[...]
Submodule a/b/c a12bc..de34f:
  > Commit 2 Message
  > Commit 1 Message
[...]
```

With `git config --global core.pager "delta --dark"` I get following output:
```
[...]
Submodule a/b/c a12bc..de34f:
----
[...]
```

I.e. the changes to the commits are not displayed any longer.

It thus appears that `delta` still mangles lines outside the changed files, in this case also the indented changes to the submodule's commits, which is in "normal diff" format (`>`/`<`).

**Comment by dandavison** [comment] 2020-04-30 18:18
Hi @fdcds Sorry this second bug has taken so long to fix. I can reproduce it. I notice that a workaround would be to use `--file-style plain` or `--color-only`, but I agree another fix to the parsing logic is still needed here.

**Comment by dandavison** [comment] 2024-08-15 11:11
Looks like this has been fixed in the intervening 5 years; I haven't bisected to find out where yet. Thanks very much @fdcds. A PR doing something in the direction of your very nice suggestion was just merged (https://github.com/dandavison/delta/pull/1787) which brought this issue to mind.

**Closed by dandavison** 2024-08-15 11:11 UTC
Labels: bug
