### ISSUE TITLE
🐛 Error message bash: delta: command not found

### ISSUE THREAD

**Issue by 1506085843** [dandavison/delta#1445] opened 2023-06-12 07:12 UTC
I installed delta and set up everything in my .gitconfig but it didn't work out of the box.
Here is my operation and error  prompt information：

```
$ delta revised.txt original.txt
bash: delta: command not found

$ git config --get core.pager
delta

$ which delta
which: no delta in (/c/Users/25371/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/25371/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/cmd:/c/Users/25371/AppData/Local/Microsoft/WindowsApps:/c/Program Files/Bandizip:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

Here is some relevant info:

```
delta  version 0.16.5  
less version  563 (PCRE regular expressions)  
git version  2.31.1.windows.1  
operating system version   win10
```
my .gitconfig:
```
[user]
	name = HaiTang

[core]
	pager = delta

[interactive]
    diffFilter = delta --color-only

[delta]
    navigate = true

[merge]
    conflictstyle = diff3

[diff]
    colorMoved = default
```

**Comment by dandavison** [comment] 2023-06-12 13:06
Hi @1506085843 , how did you install delta? Do you know where the delta executable file is?

**Comment by 1506085843** [comment] 2023-06-12 13:36
@dandavison I just downloaded delta.exe from the release page and placed it in a folder, and then I ran git bash in this folder directory

**Comment by dandavison** [comment] 2023-06-12 19:27
OK, so you have two choices:

1. Move delta.exe to a location where it will be found. For example, you could move it to `C:\Users\25371\bin`

2. Alternatively, you can tell delta where it is. You need to know the full path of the folder where you saved delta. Then, in your gitconfig, instead of just writing `pager = delta`, write out the full path to delta.

(I'm going to close this issue because it's not a bug in delta, but please feel free to ask any more questions.)

**Closed by dandavison** 2023-06-12 19:27 UTC
