### ISSUE TITLE
Terminal size is off by one on Linux

### ISSUE THREAD

**Issue by igrekster** [dandavison/delta#41] opened 2019-10-27 00:58 UTC
It appears, the detected terminal size is one character too wide:
![image](https://user-images.githubusercontent.com/1772013/67627856-20383d80-f8b0-11e9-8cff-0ce144327103.png)

I tried in Konsole-19.08.2, xterm-337, tmux-2.9a. I have not noticed any issues in other terminal apps such as `tig`.

I've tried on the latest release - 0.0.14.

**Comment by igrekster** [comment] 2019-10-27 01:37
I figured it out, it was my `~/.lesskeyrc` -- I have `-J` or `--status-column` enabled which reduces the width by one character. I wonder if it would be possible to detect it, or have a way to override.

**Comment by dandavison** [comment] 2019-10-27 06:06
Hm, this was supposed to have been fixed in v 0.0.13 by https://github.com/dandavison/delta/pull/22. Let's get to the bottom of this!

I'm not managing to reproduce yet in MacOS iTerm2 with delta 0.0.14. Here's a little experiment. Notice how, in the first case, delta is leaving one character of space unused at the right edge of the terminal. This is what is should always do by default, since #22. In the second case, `less` is invoked with `-J`, and so it inserts an extra space in the left column, but the lines do not overflow on the right because of the extra space which was left there for this reason.

Can you reproduce this? (If not, can you double check the version of `delta` that is being invoked by git (maybe pipe `git` output into a delta executable explicitly) and post the relevant contents of your `~.lesskey`).

**With `LESS` environment variable equal to empty string (`export LESS=`)**:
![image](https://user-images.githubusercontent.com/52205/67630420-6f488900-f844-11e9-87bf-40beb8b10344.png)

**With `export LESS=-J`**:
![image](https://user-images.githubusercontent.com/52205/67630417-6061d680-f844-11e9-8795-2c0f6d466ab9.png)

**Comment by dandavison** [comment] 2019-10-27 06:55
Also, if it's still mysterious, could you post the values of the environment variables `PAGER`, `BAT_PAGER` and `LESS`?

**Comment by igrekster** [comment] 2019-10-27 09:02
> Notice how, in the first case, delta is leaving one character of space unused at the right edge of the terminal. This is what is should always do by default, since #22. In the second case, less is invoked with -J, and so it inserts an extra space in the left column, but the lines do not overflow on the right because of the extra space which was left there for this reason.

Well, in my case `less -J` adds **two** spaces:

![image](https://user-images.githubusercontent.com/1772013/67632181-76c76b00-f8f4-11e9-9eae-3c3d0aa088a4.png)

I've built `git-delta` from the sources attached to the release: `https://github.com/dandavison/delta/archive/0.0.14.tar.gz`

```bash
$ delta --version
delta 0.0.14
```

My `.lesskeyrc` : `LESS=-imJMWR`

My environment:
```bash
$ env | grep -i -e '\(less\|pager\)'
LESS=-R -M --shift 5
LESSCOLOR=yes
LESSOPEN=|/usr/bin/lesspipe.sh %s
MANPAGER=manpager
PAGER=/usr/bin/less
```
I've unset all of my environment and removed the `lesskey` file, and tried the pipe mode:
```bash
$ env | grep -i -e '\(less\|pager\)'
MANPAGER=manpager
PAGER=/usr/bin/less
$ git show --color=always | delta
```
![image](https://user-images.githubusercontent.com/1772013/67632069-85148780-f8f2-11e9-833d-b19af22a90ed.png)

And with `LESS=-J`:
```bash
$ git show --color=always | LESS=-J delta
```
![image](https://user-images.githubusercontent.com/1772013/67632084-c5740580-f8f2-11e9-8c69-65fc2b8dba62.png)

I've also tried the the latest commit, which gives me the same behaviour:
```bash
$ git describe --tags
0.0.14-1-gba454ba
```
This is inside `tmux`.

**Comment by igrekster** [comment] 2019-10-27 09:37
I did a bit of digging, it appears to have changed in version 525 of `less`:

https://github.com/gwsw/less/commit/0a150b3b083a64bc1e5f2bb9582ec1bdfce137bd#diff-94003069247e17a040faa638addca45cR166

**Closed** 2019-10-27 15:57 UTC

**Comment by dandavison** [comment] 2019-10-27 16:02
Thanks! Should be fixed in master by #43, would you be able to confirm?

**Comment by igrekster** [comment] 2019-10-28 09:10
This is exactly the path I was using as a workaround ;-)
I've built and tested the latest master -- looking good, thank you very much for fixing it promptly.
```
$ git describe --tags
0.0.14-5-g4b7bbdd
```

**Comment by fdcds** [comment] 2019-11-12 18:32
I noticed the same (without using any arguments to `less`), but the effect appears to depend on the theme. I remember that the output was fine with `--dark`, but broken in this way with `--light`. I am currently on a different monitor (different resolution) and cannot reproduce it here, though.

**Comment by dandavison** [comment] 2019-11-12 18:35
@fdcds thanks! Do please let us know if you see this problem with the current version.
