### ISSUE TITLE
🐛 Configuration within `.gitconfig` is ignored

### ISSUE THREAD

**Issue by doak** [dandavison/delta#520] opened 2021-02-09 13:39 UTC
Configuration within `~/.gitconfig` is ignored if it contains some unusual (but imho correct) Git alias configuration. It seems the parser fails silently. Since the alias works like expected, I assume this is valid syntax.
Most likely this is a bug of the used parser, but at least failing silently seems to be related here.

If the Git alias configuration (see below) is changed slightly (e.g. everything in one line), it works as expected.

# How to reproduce

1. Create `~/.gitconfig` with this content:
```
[core]
    pager = delta
[interactive]
    diffFilter = delta
[delta]
    syntax-theme = ansi-light
    color-only = true
[alias]
    delta-bug = !bash -c ' \ 
        VARIABLE="test/data" \
        && echo "${VARIABLE#*/}" \
        '  
```
2.  Run `git show` within an arbitrary repository.

# Expected outcome

* Configuration (theme, color-only) is honoured.
<img src='https://user-images.githubusercontent.com/2485924/107370347-253ff100-6ae3-11eb-9c49-1a67dd6d8831.png'  width=30%>

# Actual outcome

* Default settings are used.
<img src='https://user-images.githubusercontent.com/2485924/107370372-2c66ff00-6ae3-11eb-8a2d-e8a5d83b211d.png' width=30%>

# Details

* `delta --version`: `0.6.0` (built from source, a6c8c0ebad3a6e534dbe642190d37866a68a1733)

**Comment by dandavison** [comment] 2021-02-09 16:29
Hi @doak, thanks for this. I confirmed the behavior with your example. I think as you say that this is basically a libgit2 issue. However, a quick play around indicates that there is a line in delta code where an error message could be printed out: https://github.com/dandavison/delta/blob/3fbb7394135f5979186b85ce948c9224771f6a24/src/git_config/mod.rs#L29 However, I'd need to be sure that this wouldn't also print something in non-error situations.

Incidentally, I notice that your gitconfig seems to break rust cargo (but they at least print a good message):

```
delta(master *) cargo build --release
error: failed to get `ansi_colours` as a dependency of package `git-delta v0.6.0 (/Users/dan/src/delta)`

Caused by:
  failed to initialize index git repository

Caused by:
  failed to parse config file: invalid configuration key (in /Users/dan/.gitconfig:13); class=Config (7)
```

Presumably cargo is also using libgit2.

**Comment by doak** [comment] 2021-02-10 08:10
@dandavison, thanks a lot for your response.
So I guess somebody needs to file an issue for `libgit2`. I will see if I can do, not sure if I am able to provide a simple example to  reproduce, though.

> However, I'd need to be sure that this wouldn't also print something in non-error situations.
Let me know if I can assist testing this.

I am sorry, I forgot to mention the issue with `cargo` which I experienced myself as well. In fact, only because of this I was able to locate the issue pretty fast ;)

**Comment by phil-blain** [comment] 2021-08-19 21:14
Hi @doak just a small note: I tried to reproduce and the alias caused Git itself to error with:
~~~
fatal: bad config line 9 in file /home/phb001/.gitconfig
~~~

That's because in your code block you have a trailing space after the first backslash, which Git flags as invalid. The correct snippet would be:
~~~css
[core]
    pager = delta
[interactive]
    diffFilter = delta
[delta]
    syntax-theme = ansi-light
    color-only = true
[alias]
    delta-bug = !bash -c ' \
        VARIABLE="test/data" \
        && echo "${VARIABLE#*/}" \
        '  
~~~

I encourage you to submit this issue to libgit2, they seem to be glad to improve the parser, even for edge cases (see for example https://github.com/libgit2/libgit2/issues/5459).

(P.S. I'm used `~~~css` to start my code block above in order to get nice syntax highlighting :P)

**Comment by dandavison** [comment] 2021-08-21 03:30
Thanks @phil-blain and @doak. I'm going to close this on the basis that we're not planning to address it in the delta codebase, but do feel free to re-open or comment more.

**Closed by dandavison** 2021-08-21 03:30 UTC
