### ISSUE TITLE
Vim terminal issue displaying colored output by delta

### ISSUE THREAD

**Issue by iago-pssjd** [dandavison/delta#1463] opened 2023-06-30 08:47 UTC
Does vim/nvim have the ability to run a shell and display colored output from the shell faithfully within the vim/nvim application? If there's something like that that works well, then it suggests that the required technology exists already.

_Originally posted by @dandavison in https://github.com/dandavison/delta/issues/338#issuecomment-699505886_
            

I recently installed and configured delta and try to use with ViM, but I got an issue. "New" lines are not overcoloured by green.

The process is, having ViM open, to use the ViM terminal through `:term` and inside that terminal using `git diff`. However it does not get fully coloured.

In the next screenshot, the left is git diff in an external terminal (bash), while the right is the `git diff` inside the ViM terminal

![extvsvimterm](https://user-images.githubusercontent.com/40892925/250042414-9a764bd1-cd11-40e7-97ea-75826efb82b8.png)

However, it does not happen without using delta. Next screenshot is of Vim terminal

![Screenshot_2023-06-30_10-55-04](https://github.com/dandavison/delta/assets/40892925/f8109dc1-a5d2-4cc1-8997-7ec7b4d95a8d)

**Comment by dandavison** [comment] 2023-06-30 11:07
Hi @iago-pssjd, that suggests that the Vim terminal you're using doesn't support a feature that terminal emulators usually support -- sounds like maybe it's not supporting the ANSI fill-to-end-of-line sequence. Can you try with the delta `width=variable` option?

**Comment by iago-pssjd** [comment] 2023-06-30 11:25
Thanks @dandavison 

I tried it, but I got the same behaviour. I paste below where I place the `width=variable` option to be sure I did right or otherwise let me know.
```
[delta]
    navigate = true    # use n and N to move between diff sections
    light = false      # set to true if you're in a terminal w/ a light background color (e.g. the default macOS terminal)
    line-numbers = true
    width = variable

```

**Comment by dandavison** [comment] 2023-06-30 11:45
OK, I think this is a bug or known limitation in the Vim terminal emulation. Can you try this command in your Vim terminal and a normal terminal?

```
echo -e "\033[44mThis line will have a blue background.\033[K\033[0m\nThis line will be normal."
```

For me in alacritty I see

<img width="1440" alt="image" src="https://github.com/dandavison/delta/assets/52205/0d528b2e-459e-47e5-82bd-50a599d3631a">

(But I blame GPT4 if there's something wrong in the way that demo command uses ANSI escapes :) )

**Comment by iago-pssjd** [comment] 2023-06-30 11:53
It works the same in both terminals!, like for you!

**Comment by dandavison** [comment] 2023-06-30 11:59
Hm, OK. Well, I think the thing to do here is isolate exactly which ANSI escape sequence it is that delta's emitting but Vim is not handling correctly. I believe that this is not a bug in delta since this bug has not been reported in any other terminal emulator.

I'll post here if it comes to me what the problem might be but meanwhile, you can see the ANSI escapes delta is emitting by doing e.g. `git show | delta | cat -A`

(which is nice with bat instead of cat)

I'm going to close this if you don't mind because I don't think there's any delta development to do, but we can definitely carry on discussing here. The close is just to indicate that for now we're not aware of delta work needed.

**Closed by dandavison** 2023-06-30 11:59 UTC

**Comment by iago-pssjd** [comment] 2023-06-30 14:42
@dandavison 

Ok! I run `git show | delta | cat -A` in both the external terminal and in the ViM terminal and the unique difference is that the long lines seem to be broken in multiple lines in the ViM terminal. After collapsing these broken lines, the output is the same.
